START /W  " "  "%SFDIR%WSFplot" rfq_a1.t35 3
START /W  " "  "%SFDIR%WSFplot" rfq_b1.t35 3
START /W  " "  "%SFDIR%WSFplot" rfq_c1.t35 3
START /W  " "  "%SFDIR%WSFplot" rfq_d1.t35 3
START /W  " "  "%SFDIR%WSFplot" rfq_d2.t35 3
START /W  " "  "%SFDIR%WSFplot" rfq_d3.t35 3
START /W  " "  "%SFDIR%WSFplot" rfq_e1.t35 3
START /W  " "  "%SFDIR%WSFplot" rfq_f1.t35 3

START /W  " "  "%SFDIR%WSFplot" la1.t35 3
START /W  " "  "%SFDIR%WSFplot" la2.t35 3
START /W  " "  "%SFDIR%WSFplot" la3.t35 3
START /W  " "  "%SFDIR%WSFplot" la4.t35 3
